"use client";
import {useEffect,useRef,useState} from "react";
import {Direction,Round,ended,freshRound,moveBoard,spawn,validRound} from "./night-game-engine";
const KEY="reiko-yoi-2048-v1";
type Saved={round:Round;previous:Round|null;best:number;games:number;sound:boolean};
export default function NightGame(){
 const [open,setOpen]=useState(false),[crossing,setCrossing]=useState(false),[state,setState]=useState<Saved|null>(null),[restart,setRestart]=useState(false),[message,setMessage]=useState("");
 const dialog=useRef<HTMLDialogElement>(null),trigger=useRef<HTMLButtonElement>(null),wing=useRef<HTMLImageElement>(null),timers=useRef<number[]>([]),audio=useRef<AudioContext|null>(null),pointer=useRef<{x:number;y:number}|null>(null);
 useEffect(()=>{let saved:Saved|null=null;try{const raw=JSON.parse(localStorage.getItem(KEY)||"null");if(raw&&validRound(raw.round))saved={round:raw.round,previous:validRound(raw.previous)?raw.previous:null,best:Number.isSafeInteger(raw.best)&&raw.best>=0?Math.max(raw.best,raw.round.score):raw.round.score,games:Number.isSafeInteger(raw.games)&&raw.games>0?raw.games:1,sound:raw.sound!==false};}catch{}setState(saved||{round:freshRound(),previous:null,best:0,games:1,sound:true});return()=>{timers.current.forEach(clearTimeout);void audio.current?.close();};},[]);
 useEffect(()=>{if(!state)return;try{localStorage.setItem(KEY,JSON.stringify(state));}catch{setMessage("浏览器未允许保存，这一局只能暂时保留。");}},[state]);
 useEffect(()=>{if(!open)return;const old=document.body.style.overflow;document.body.style.overflow="hidden";dialog.current?.showModal();return()=>{dialog.current?.close();document.body.style.overflow=old;trigger.current?.focus({preventScroll:true});};},[open]);
 function close(){timers.current.forEach(clearTimeout);timers.current=[];setCrossing(false);setOpen(false);setRestart(false);pointer.current=null;}
 function ring(){if(!state?.sound)return;try{const a=audio.current||(audio.current=new AudioContext());void a.resume();const t=a.currentTime;[880,2376,3920].forEach((frequency,i)=>{const oscillator=a.createOscillator(),gain=a.createGain();oscillator.type="sine";oscillator.frequency.setValueAtTime(frequency,t);gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(.026/(i+1),t+.008);gain.gain.exponentialRampToValueAtTime(.0001,t+1.35-i*.18);oscillator.connect(gain);gain.connect(a.destination);oscillator.start(t);oscillator.stop(t+1.4);oscillator.onended=()=>{oscillator.disconnect();gain.disconnect();};});}catch{}}
 function enter(){if(!state||open)return;ring();setOpen(true);if(window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;setCrossing(true);const started=performance.now();function frame(){const index=Math.min(14,Math.floor((performance.now()-started)/75));if(wing.current)wing.current.src=`/reiko-assets/oumagatoki/red-butterfly/red_butterfly_${index+1}.png`;if(performance.now()-started<1350)timers.current.push(window.setTimeout(frame,75));}timers.current.push(window.setTimeout(frame,30),window.setTimeout(()=>setCrossing(false),1350));}
 function move(direction:Direction){if(crossing||restart)return;setState(current=>{if(!current||ended(current.round.board))return current;const result=moveBoard(current.round.board,direction);if(!result.changed)return current;const round={board:spawn(result.board),score:current.round.score+result.gained};return {...current,round,previous:current.round,best:Math.max(current.best,round.score)};});}
 useEffect(()=>{if(!open)return;function key(event:KeyboardEvent){const keys:Record<string,Direction>={ArrowLeft:"left",ArrowRight:"right",ArrowUp:"up",ArrowDown:"down"};if(keys[event.key]){event.preventDefault();move(keys[event.key]);}}window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);});
 const over=state?ended(state.round.board):false;
 return <section className="dusk-section yoi-play-section" aria-label="夜遊小游戏"><button ref={trigger} type="button" className="yoi-play-entrance" onClick={enter} disabled={!state} aria-label="打开夜遊 2048"><img src="/reiko-assets/oumagatoki/night-play.png" alt="雨檐下的旧铃与暗红木框，远处有一盏灯" loading="lazy"/><span className="yoi-entrance-mist"/><img className="yoi-entrance-frame" src="/reiko-assets/oumagatoki/night-frame.webp" alt="" loading="lazy"/><span className="yoi-entrance-copy"><small>宵伽 / AFTER HOURS</small><strong>夜遊</strong><span>听一声铃，留一局夜。</span><em>2048 · 点此进入 →</em></span><span className="yoi-entrance-record">{state&&state.best>0?`最高分 ${state.best}`:"一局未尽，夜还很长。"}</span></button>
 {open&&state&&<dialog ref={dialog} className={`yoi-game-dialog ${crossing?"is-crossing":""}`} aria-label="夜遊 2048" onCancel={event=>{event.preventDefault();close();}}><button className="yoi-game-close" type="button" onClick={close} aria-label="合上夜遊，保留棋局">×</button><div className="yoi-game-content" inert={crossing}><header><span>宵伽 / 夜遊</span><h2>2048</h2><p>让相同的数字，在夜里相遇。</p></header><div className="yoi-game-scores"><span>这一局 <b>{state.round.score}</b></span><span>最高分 <b>{state.best}</b></span><span>局数 <b>{state.games}</b></span></div><div className="yoi-board-wrap"><img className="yoi-board-decoration" src="/reiko-assets/oumagatoki/night-board-decoration.webp" alt=""/><div className="yoi-board" role="group" aria-label="2048 棋盘，方向键或滑动移动" tabIndex={0} onPointerDown={event=>{if(event.pointerType==="mouse")return;pointer.current={x:event.clientX,y:event.clientY};event.currentTarget.setPointerCapture(event.pointerId);}} onPointerCancel={()=>{pointer.current=null;}} onPointerUp={event=>{if(!pointer.current)return;const x=event.clientX-pointer.current.x,y=event.clientY-pointer.current.y;pointer.current=null;if(Math.max(Math.abs(x),Math.abs(y))<24)return;move(Math.abs(x)>Math.abs(y)?x>0?"right":"left":y>0?"down":"up");}}>{state.round.board.map((value,index)=><div key={index} className={`yoi-cell yoi-value-${Math.min(value,2048)}`} aria-label={`第${Math.floor(index/4)+1}行，第${index%4+1}列，${value||"空"}`}><span key={value}>{value||""}</span></div>)}</div></div><p className="yoi-game-status" role="status">{over?"这一局停在这里。再听一声铃，重新开始。":state.round.board.includes(2048)?"已合成 2048，仍可继续夜遊。":"方向键 / 滑动 · 也可点下方方向"}</p><div className="yoi-direction-pad">{(["left","up","down","right"] as Direction[]).map((direction,index)=><button type="button" key={direction} onClick={()=>move(direction)} disabled={over||restart} aria-label={`向${["左","上","下","右"][index]}移动`}>{["←","↑","↓","→"][index]}</button>)}</div><div className="yoi-game-actions"><button type="button" disabled={!state.previous||restart} onClick={()=>setState(current=>current?.previous?{...current,round:current.previous,previous:null}:current)}>撤回一步</button><button type="button" onClick={()=>setRestart(true)}>重新开始</button><button type="button" aria-pressed={state.sound} onClick={()=>setState({...state,sound:!state.sound})}>铃声{state.sound?"开":"关"}</button></div>{restart&&<div className="yoi-game-confirm"><p>结束这一局，开始新的一局？</p><button type="button" onClick={()=>{ring();setState({...state,round:freshRound(),previous:null,games:state.games+1});setRestart(false);}}>开始新局</button><button type="button" onClick={()=>setRestart(false)}>继续这一局</button></div>}<small className="yoi-game-storage">棋局与最高分保存在此浏览器 · 合上后可继续</small>{message&&<p role="status">{message}</p>}</div>{crossing&&<div className="yoi-wing-crossing" aria-hidden="true"><div className="yoi-wing-veil"/><img ref={wing} src="/reiko-assets/oumagatoki/red-butterfly/red_butterfly_1.png" alt=""/></div>}</dialog>}
 </section>;
}
